### PR TITLE
add dependencies necessary for building docs

### PR DESCRIPTION
**Pull request by bleything**
#### Description

While working on #305 I needed to install several packages in order to build the docs. This adds those packages to the dev dependencies.

#### Checklist

- [X] feature/fix implemented
- [X] `mypy` returns no error
- [X] tests added/updated and `pytest --runslow` succeeds
- [X] documentation added/updated and building with no error (`make clean && make html` in `docs/`)
- [ ] ~examples added/updated~ (not applicable)
- [X] code formatting ok (`black` and `isort`)

### CODE REVIEW

**Comment by abey79** [comment]
Oh yeah, currently they are in `docs/requirement.txt`, which is the current reference used by RTD for build (as per `.readthedocs.yml`. I meant to put that back in `pyproject.toml` using poetry 1.2 style group, like I did for vpype (https://github.com/abey79/vpype/pull/541).

**Comment by abey79** [comment]
on top of my head, here is what would be needed to bring that in sync with how it's done in vpype:

1) set the deps as follows in `pyproject.toml`:
```toml
[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx = ">=5.0.2"
...
```

2) change `.readthedocs.yml` to:

```yaml
# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    post_install:
      - pip install poetry>=1.2.1
      - poetry config virtualenvs.create false
      - poetry install --with docs
```

3) delete `docs/requirements.txt`

4) probably update readme/docs? (`poetry install --with docs` for full install)

Any chance you can spare the time to give this a look?

**Comment by bleything** [comment]
I'll give it a shot and see. This is definitely beyond my python expertise, though :)

**Comment by bleything** [comment]
okay, I've made the suggested changes and confirmed that I can build the docs locally

**Comment by abey79** [comment]
Thanks! I added/fixed a few things on the way.

**Pull request merged**
